# Generated by Django 4.0.5 on 2022-06-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwwards_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projects'),
        ),
    ]
